# Generated by Django 6.0.3 on 2026-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='destination',
            new_name='location_area',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='nairobi', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
