# Generated by Django 6.0.3 on 2026-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_destination_order_location_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
