# Generated by Django 6.0.3 on 2026-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_destination_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
