# Generated by Django 6.0.3 on 2026-03-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_discount_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
    ]
