# Generated by Django 6.0.3 on 2026-04-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_image'),
    ]

    operations = [
    ]
