# Generated by Django 6.0.3 on 2026-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20260401_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
