# Generated by Django 6.0.3 on 2026-04-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_options_remove_order_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='nairobi', max_length=255),
            preserve_default=False,
        ),
    ]
