# Generated by Django 6.0.3 on 2026-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee_nairobi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_fee_outside', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('discounts_active', models.BooleanField(default=True, help_text='Uncheck to ignore discounted prices and use original prices.')),
                ('discount_message', models.CharField(blank=True, help_text="Optional banner text (e.g. 'Easter Sale 20% Off!')", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_expiry',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='How many hours should the discount last?'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_time',
            field=models.DateTimeField(blank=True, help_text='When the discount was activated.', null=True),
        ),
    ]
