# Generated by Django 6.0.3 on 2026-04-04 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sitesettings_remove_product_discount_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='discount_message',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='shipping_fee_outside',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='discounts_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='productview',
            unique_together={('user', 'product')},
        ),
    ]
