# Generated by Django 6.0.3 on 2026-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_sitesettings_discount_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
