# Generated by Django 6.0.3 on 2026-04-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_useractivity_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief catchy description (max 300 characters).', max_length=300, null=True),
        ),
    ]
