# Generated by Django 6.0.3 on 2026-05-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_signupotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_fee',
            new_name='shipping_fees',
        ),
    ]
