# Generated by Django 6.0.3 on 2026-05-11 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_shipping_fee_product_shipping_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(choices=[('nairobi', 'Nairobi'), ('outside', 'Upcountry')], default='nairobi', max_length=20)),
                ('nairobi_area', models.CharField(blank=True, max_length=100, null=True)),
                ('upcountry_county', models.CharField(blank=True, max_length=100, null=True)),
                ('upcountry_town', models.CharField(blank=True, max_length=100, null=True)),
                ('address_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
